import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:food_footprint/base/colors.dart';

class CarbonFootPrint extends StatefulWidget {
  const CarbonFootPrint({super.key});

  @override
  State<CarbonFootPrint> createState() => _CarbonFootPrintState();
}

class _CarbonFootPrintState extends State<CarbonFootPrint> {
  @override
  Widget build(BuildContext context) {
    final TextTheme theme = Theme.of(context).textTheme;
    return Scaffold(
      body: body(theme: theme),
    );
  }

  Widget body({TextTheme? theme}) {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 15),
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              GestureDetector(
                onTap: () {
                  Navigator.pop(context);
                },
                child: Container(
                  width: 36.w,
                  height: 36.w,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    color: AppColors.gray3,
                  ),
                  child: Icon(
                    Icons.close,
                    size: 30,
                    color: AppColors.white,
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(top: 10, bottom: 15),
                child: Text(
                  'Carbon FootPrint – Effects & How to Reduce it?',
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                "Ever wondered how your daily activities impact the planet? Welcome to the world of Carbon Footprints, a crucial measure of our environmental impact. This guide delves into what carbon footprints are, how they’re calculated, and why understanding them is key to making more sustainable choices. From the food we eat to the cars we drive, every action contributes to our carbon footprint. Let’s explore how we can reduce this footprint and pave the way for a greener, more sustainable future.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 15),
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(15),
                  child: Image.asset(
                    "assets/article/article3.png",
                    height: 200,
                    width: double.infinity,
                    fit: BoxFit.fill,
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  'What is Carbon footprint?',
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "Carbon footprint is a very important aspect to assess the impact of carbon dioxide emissions on the environment and also the role of people, organizations, and society to make this happen day by day. The more you pollute the environment with your actions, the deeper you make the carbon footprint on the earth. Carbon footprint is measured as the total amount of green gasses including carbon dioxide that is generated by our conscious actions, choices, and habits.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  'Table of Content',
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                '. What is Carbon footprint?\n. Components of Carbon Footprint\n. Effects of Carbon Footprint\n. Major Factors Contributing to Carbon Footprint\n. Ways To Reduce Carbon Footprint\n. Important Data On Carbon Footprint\n. Innovations in Carbon Reduction\n. Importance of Education and Awareness',
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "Components of Carbon Footprint",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "The carbon footprint takes into account the amount of greenhouse gas emissions and is measured in terms of an individual’s contribution to it. The gasses primarily comprise carbon dioxide and methane that are produced through various activities like industrial operations, burning of fuels, and the production and consumption of various products and services. The major part is the emissions due to fuel combustion happening during transportation. Domestic and commercial activities also cause the emission of carbon dioxide and other gasses. It also includes the generation of harmful components emitted during the production of electricity and other industrial activities that pollutes air, water, and soil. Carbon footprint increases due to waste generation that is not processed through adequate waste recycling procedures. The carbon footprint also focuses on the greenhouse gas emissions associated with goods and services that are consumed by personnel at the individual and community level. Fuel combustion, water pollution, and emissions of harmful gasses are major contributors to the carbon footprint.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(
                  vertical: 10,
                ),
                child: Text(
                  'Effects of Carbon Footprint',
                  style: theme?.headlineMedium,
                ),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "1. Effect On the Environment",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "The most critical effect of carbon footprint is that it is adversely affecting the environment that we live in. As a result of an increased proportion of carbon dioxide in the atmosphere, a rise in temperatures, prolonged showers, tropical storms, wildfires, and other unusual climate changes are happening. Global Warming causes the melting of ice and rise in sea levels that are destroying coastal habitats. All these changes in climatic conditions are affecting the growing patterns of plants and vegetation which eventually is destroying the ecosystem.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "2. Affecting Wildlife",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "The inconsistent weather patterns resulting from increasing pollution and global warming are posing danger in the lives of various wildlife species driving them close to extinction. The interdependence between plants and animals is getting disturbed and thereby causes starvation, displacement, and extinction. The absence of natural habitats and increased pollution levels are affecting biodiversity patterns on earth which is a threat to the existence of living creatures on this planet.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "3. Impact On Human Health",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "Climate change, drought, and floods affect the natural growth of food crops which in turn can result in poor crop production, increased malnutrition, and health issues. Moreover, people are getting affected by various diseases due to excess pollution of air, soil, and water. The compromised Air Quality Index in urban areas has led to an increase in respiratory-related problems like asthma, bronchitis, and allergies.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "4. Retards Economic Growth",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "The reduction in carbon footprint has become extremely important because it contributes to slow economic growth in the country. Several studies have revealed that climate change and pollution affect the agricultural and natural resources of a country. As a result, countries dependent majorly on agriculture and cultivation face slow progress in economic growth and lower revenue earnings.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(
                  vertical: 10,
                ),
                child: Text(
                  'Major Factors Contributing to Carbon Footprint',
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                "Our carbon footprint shows how much greenhouse gases, mainly CO2, come from what we do, both directly and indirectly. Here are some of the factors contributing to carbon footprint:\n. Fossil Fuel-Based Energy Consumption: Burning fossil fuels like coal, oil, and natural gas releases significant amounts of CO2 into the atmosphere. Our reliance on these fuels for electricity, transportation, and heating contributes significantly to our individual and collective carbon footprint.\n. Deforestation and Land Use Change: Clearing forests for agriculture, logging, and other purposes releases stored carbon dioxide and reduces the planet’s ability to absorb carbon. This factor is especially significant in regions with high deforestation rates, like the Amazon rainforest.\n. Industrial Processes: Many industrial processes, including manufacturing, cement production, and steelmaking, release greenhouse gases as byproducts. While these emissions can vary greatly depending on the specific industry and technology used, they still contribute significantly to global carbon footprint.\n. Agriculture and Livestock Production: Agricultural practices like intensive farming, fertilizer use, and animal agriculture generate significant greenhouse gases like methane and nitrous oxide. Reducing food waste, adopting sustainable agricultural practices, and shifting towards plant-based diets can help mitigate emissions from this sector.\n. Transportation: The transportation sector is a major contributor to carbon emissions, primarily due to our reliance on individual vehicles like gasoline-powered cars and trucks. Public transportation, cycling, walking, and electric vehicles offer alternative low-carbon transportation options.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(
                  vertical: 10,
                ),
                child: Text(
                  "Ways To Reduce Carbon Footprint",
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                "As responsible citizens, we should take initiative and make conscious efforts to reduce the emission of carbon dioxide and other toxic elements in the environment. Almost all the sectors including manufacturing, transportation, and even agriculture are responsible for the increased carbon footprint in a country. All nations need to evolve some effective measures to control the increasing trend of greenhouse gas emissions affecting flora and fauna, biodiversity, and human lives. Some of the simple but effective steps that need to be taken to reduce carbon footprint are as follows:",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "1. Use of Sustainable and Clean Energy Resources:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "It is extremely necessary to cut down the usage of fossil fuels for energy production on a large scale. It would help to reduce the emission of harmful gasses when these fuels are burnt. Priority is to be given to cleaner and greener energy production like solar power.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "2. Reduce and Recycle Waste:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "Reduction in waste generation that is not biodegradable is a major step to reduce carbon footprint. Choose reusable or single-use materials and refuse to use that can’t be recycled. The production, consumption, and end-use of products generate a lot of waste and are major contributors to harmful gas emissions in the atmosphere. Reduction in food waste will help in minimizing consumption and production, and the gas emissions associated with it.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "2. Reduce and Recycle Waste:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "Reduction in waste generation that is not biodegradable is a major step to reduce carbon footprint. Choose reusable or single-use materials and refuse to use that can’t be recycled. The production, consumption, and end-use of products generate a lot of waste and are major contributors to harmful gas emissions in the atmosphere. Reduction in food waste will help in minimizing consumption and production, and the gas emissions associated with it.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "3. Change In Lifestyle And Habits:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "It is high time that we, as individuals, try to realize the serious effects of the carbon footprint on our lives and should take every step to control it. It can be done easily by bringing some changes in our habits and choices.\n. Avoid excess electricity consumption by using energy-efficient lamps and setting the optimum temperature of thermostats in air-conditioners. Installing draught-proofing kits helps you control the room temperature and make your home energy-efficient.\n. Using public transport like train, bus, etc., or walking for short distances instead of driving a car can contribute to a great extent to the reduction in carbon footprint.\n. You can modify your habits to buy more local foods and make changes in your lifestyle by using second-hand products to reduce the demand for more production of consumables.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "Understanding Carbon Footprint Calculation",
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                "Calculating a carbon footprint involves assessing the total amount of greenhouse gases produced directly and indirectly by a person, organization, event, or product. This calculation is typically done in terms of carbon dioxide equivalents (CO2e), which measure the impact of different greenhouse gases in terms of the amount of CO2 that would create the same amount of warming.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "Key Components in Carbon Footprint Calculation",
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                "1. Energy Consumption: This includes electricity, heating, and cooling. The amount of energy used is converted into CO2e based on the energy source. For example, coal-powered electricity generates more CO2e compared to renewable sources.\n2. Transportation: This covers personal and public transportation. Emissions are calculated based on the type of vehicle, fuel efficiency, and distance traveled. Air travel is also a significant contributor to individual carbon footprints.\n3. Food Consumption: The type of diet one follows impacts their carbon footprint. Meat-based diets generally have a higher footprint compared to plant-based diets, due to the resources required for livestock farming and associated methane emissions.\n4. Goods and Services: The production, transportation, and disposal of goods and services we use contribute to our carbon footprint. This includes everything from clothing and electronics to services like banking and healthcare.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "Methods of Calculation",
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                ". Life Cycle Assessment (LCA): This method evaluates the environmental impacts associated with all the stages of a product’s life, from raw material extraction through materials processing, manufacture, distribution, use, repair and maintenance, and disposal or recycling.\n. Carbon Footprint Calculators: Various online tools are available for individuals and organizations to estimate their carbon footprint. These calculators often use generalized data and user inputs about lifestyle choices, consumption patterns, and travel habits.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "Importance of Accurate Calculation",
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                ". Accurate carbon footprint calculation is crucial for understanding the impact of our actions on the environment. It helps in identifying key areas where changes can be made to reduce emissions.\n. For businesses, it’s essential for setting and meeting sustainability goals, improving resource efficiency, and enhancing corporate responsibility.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "Important Data On Carbon Footprint",
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                ". The global average carbon footprint is about 4 tons per person with the highest in the United States (16 tons).\n. One-fourth of the earth’s species are likely to face extinction within the next 40 years if climate change continues to increase at the current rate.\n. Reduction in greenhouse gas emissions can help prevent up to 3 million premature deaths yearly by the year 2100.\n. If each of the 140 million homes in a city replaces its incandescent light bulb with an energy-efficient CFL lamp, it can save enough energy to power over 3 million homes in a year.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "Innovations in Carbon Reduction",
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                "Innovations keep coming to help cut carbon footprints beyond the usual green tech. Here are some new and promising solutions:",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "1. Direct Air Capture (DAC):",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "Direct Air Capture or DAC technology grabs CO2 straight from the air, aiming to fix past emissions and ease climate change. It’s new but has big potential to remove lots of carbon.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "2. Bioenergy with Carbon Capture and Storage (BECCS):",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "BECCS mixes making energy from plants with capturing CO2. It takes CO2 from the process and stores it underground. This can actually remove CO2 from the air, helping fight climate change.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "3. Green Hydrogen Technology:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "Hydrogen produced using renewable energy sources, known as green hydrogen, has the potential to decarbonize various sectors, including transportation, industry, and power generation.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "4. Circular Economy Principles:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "The circular economy helps use resources well and makes less waste. It does this by using closed-loop systems, making long-lasting and fixable products, and encouraging recycling and reusing. This helps cut down on carbon footprints in different industries.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "5. Blockchain for Carbon Tracking and Transparency:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                "Blockchain helps show carbon data clearly and securely. It uses distributed ledgers to give accurate and unchangeable info on carbon emissions. This helps track, check, and reduce emissions effectively.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "Importance of Education and Awareness",
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                "Education and awareness play a key role in tackling climate change by reducing carbon footprints. Here’s why they matter:\n\n. Understanding the Impact: It helps people grasp the idea of carbon footprints and how they affect the environment. It shows the link between daily choices and climate change, encouraging responsibility and action.\n. Making Smart Choices: It allows people to make better choices. Education offers tools to measure carbon footprints, find areas for improvement, and pick eco-friendly options in travel, energy use, shopping, and waste disposal.\n. Changing Behavior: Awareness campaigns can shift society towards eco-friendly living. By showcasing benefits like cleaner air, saving money, and healthier communities, they motivate people to embrace sustainable habits.\n. Building a Movement: Teaching the public creates a group of informed citizens. This lets people push for big changes, hold companies and governments accountable, and ask for rules supporting a greener future.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "Real-World Examples of Carbon Footprint Reduction Strategies:",
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                "1. Renewable Energy Adoption: Countries like Denmark and Germany have made significant strides in adopting renewable energy sources. Denmark, for instance, aims to be free of fossil fuels by 2050, with wind power already accounting for a substantial portion of its energy production.\n2. Electric Vehicle Initiatives: Norway leads in electric vehicle adoption, with policies that include tax exemptions, toll waivers, and free parking for electric vehicle owners. This shift significantly reduces carbon emissions from transportation.\n3. Sustainable City Planning: Singapore is an excellent example of sustainable urban development. The city-state incorporates green spaces, promotes public transportation, and implements strict building codes to enhance energy efficiency.\n4. Corporate Carbon Neutrality: Companies like Google and Microsoft have committed to carbon neutrality. Google uses high-efficiency data centers and renewable energy, while Microsoft has implemented an internal carbon fee to fund sustainability projects.\n5. Community-Based Projects: In Kenya, the Green Belt Movement has planted over 51 million trees, combating deforestation and reducing carbon emissions. This grassroots initiative also empowers communities through education and conservation activities.\n6. Agricultural Innovations: In California, the Sustainable Agriculture and Energy (SAGE) program helps farmers adopt sustainable practices, such as solar-powered irrigation and crop rotation, to reduce their carbon footprint.\n7. Waste Management in Sweden: Sweden’s advanced waste management systems convert waste into energy, significantly reducing landfill use and greenhouse gas emissions. The country imports waste from other European nations for energy production.\n8. Eco-Friendly Tourism in Costa Rica: Costa Rica’s commitment to eco-tourism involves protecting natural habitats and promoting sustainable travel practices, which helps in reducing the carbon footprint associated with tourism.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "Global Initiatives for Carbon Footprint Reduction",
                  style: theme?.headlineMedium,
                ),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "1. Paris Agreement on Climate Change:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                ". A landmark international accord adopted by nearly every nation in 2015, aiming to limit global warming and reduce greenhouse gas emissions. Countries commit to ambitious climate actions and report on their emissions and implementation efforts.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "2. United Nations Sustainable Development Goals (SDGs):",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                ". The SDGs, particularly Goal 13 (Climate Action), encourage nations to take urgent action to combat climate change and its impacts. This includes measures to reduce carbon emissions and promote renewable energy.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "3. Intergovernmental Panel on Climate Change (IPCC):",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                ". The IPCC provides scientific reports that guide policymakers. It plays a crucial role in understanding the extent of climate change and the necessary actions to mitigate it, including carbon footprint reduction strategies.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "4. Green Climate Fund:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                ". Established within the framework of the United Nations Framework Convention on Climate Change (UNFCCC), this fund assists developing countries in adaptation and mitigation practices to counter climate change.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "5. International Carbon Reduction and Offset Alliance (ICROA):",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                ". ICROA promotes voluntary carbon offsetting and reduction through market-based mechanisms, helping businesses and individuals to compensate for their emissions by investing in environmental projects.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "6. Global Carbon Pricing Initiatives:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                ". Various carbon pricing mechanisms, like carbon taxes and cap-and-trade systems, are implemented by countries to incentivize the reduction of carbon emissions.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "7. Renewable Energy Initiatives:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                ". International efforts such as the International Solar Alliance and wind energy projects aim to increase the use of renewable energy sources, thereby reducing reliance on fossil fuels.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "8. Reforestation and Afforestation Projects:",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Text(
                ". Global initiatives like the Bonn Challenge and Trillion Tree Campaign focus on restoring and planting trees to absorb CO2 from the atmosphere.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.only(top: 10),
                child: Text(
                  "Conclusion",
                  style: theme?.headlineMedium,
                ),
              ),
              Text(
                "On average, it’s about 4.8 tons per person yearly worldwide, but this varies based on how people live, where they are, and what they use. Things like transport, energy, food, and cutting down forests create a lot of these gases, causing problems like climate change, higher seas, extreme weather, and harm to nature. It’s really important to take quick steps to reduce these gases and deal with the serious effects of climate change. We should not be silent observers of the increased environmental pollution leading to global warming, and climate changes. Every individual at a personal level and as part of a community and nation must ensure not to put any permanent damaging mark on earth in the form of a carbon footprint. It is the time to increase awareness among more and more people to start taking steps from the domestic level and spread it across the organizational, industrial, and national levels.",
                style: theme?.titleSmall?.copyWith(color: AppColors.grayLight),
              ),
              Padding(
                padding: const EdgeInsets.only(top: 10),
                child: Text(
                  "FAQs on Carbon Footprint",
                  style: theme?.headlineMedium,
                ),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "1. What is the definition of carbon footprint?",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Container(
                padding: EdgeInsets.all(8),
                decoration: BoxDecoration(
                    color: AppColors.gray1,
                    borderRadius: BorderRadius.circular(10)),
                child: Text(
                  "A carbon footprint is the total amount of greenhouse gases, primarily carbon dioxide (CO2), emitted directly and indirectly by an individual, organization, or activity.",
                  style:
                      theme?.titleSmall?.copyWith(color: AppColors.grayLight),
                ),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "2. What is an example of carbon footprint?",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Container(
                padding: EdgeInsets.all(8),
                decoration: BoxDecoration(
                    color: AppColors.gray1,
                    borderRadius: BorderRadius.circular(10)),
                child: Text(
                  "The carbon footprint of driving a car for 10 miles can be around 20 pounds of CO2, depending on the fuel efficiency of the vehicle. This is because burning gasoline releases CO2 as a byproduct. ",
                  style:
                      theme?.titleSmall?.copyWith(color: AppColors.grayLight),
                ),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "3. Is carbon footprint good or bad?",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Container(
                padding: EdgeInsets.all(8),
                decoration: BoxDecoration(
                    color: AppColors.gray1,
                    borderRadius: BorderRadius.circular(10)),
                child: Text(
                  "In itself, the concept of carbon footprint is not inherently good or bad. It is a metric used to measure our impact on the environment. However, a high carbon footprint is generally considered negative, as it signifies a significant contribution to greenhouse gas emissions and climate change.",
                  style:
                      theme?.titleSmall?.copyWith(color: AppColors.grayLight),
                ),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "4. How is a carbon footprint calculated?",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Container(
                padding: EdgeInsets.all(8),
                decoration: BoxDecoration(
                    color: AppColors.gray1,
                    borderRadius: BorderRadius.circular(10)),
                child: Text(
                  "arbon footprints can be calculated using various online tools and calculators. These tools typically require information such as energy consumption, transportation habits, diet, and consumption of goods and services.",
                  style:
                      theme?.titleSmall?.copyWith(color: AppColors.grayLight),
                ),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 10),
                child: Text(
                  "5. Is carbon footprint harmful to humans?",
                  style: theme?.titleMedium?.copyWith(fontSize: 15),
                ),
              ),
              Container(
                padding: EdgeInsets.all(8),
                decoration: BoxDecoration(
                    color: AppColors.gray1,
                    borderRadius: BorderRadius.circular(10)),
                child: Text(
                  "Carbon footprint is not directly harmful to humans. However, the high levels of greenhouse gases it represents contribute to climate change, which can have various negative impacts on human health and well-being. ",
                  style:
                      theme?.titleSmall?.copyWith(color: AppColors.grayLight),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
