Map<String, dynamic> productInformation = {
  "Meat and Poultry": {
    "Beef": {
      "image": "assets/product/beef.png",
      "isFavorite": false,
      "Carbon Footprint": "27 kg CO₂ per kg",
      "Environmental Impact":
          "High methane emissions, deforestation for grazing",
      "Seasonality": "Year-round (high carbon footprint regardless)",
      "Transportation": "High for imports",
      "Alternative": ["Lentils", "Beans"],
    },
    "Pork": {
      "image": "assets/product/pork.png",
      "isFavorite": false,
      "Carbon Footprint": "12.1 kg CO₂ per kg",
      "Environmental Impact": "Moderate, requires water and feed resources",
      "Seasonality": "Year-round",
      "Transportation": "Moderate, often locally sourced",
      "Alternative": ["Chicken", "Chickpeas"],
    },
    "Chicken": {
      "image": "assets/product/chicken.png",
      "isFavorite": false,
      "Carbon Footprint": "6.9 kg CO₂ per kg",
      "Environmental Impact":
          "Lower than red meat but still requires resources",
      "Seasonality": "Year-round",
      "Transportation": "Low for local farms",
      "Alternative": ["Tofu", "Mushrooms"],
    },
    "Turkey": {
      "image": "assets/product/turkey.png",
      "isFavorite": false,
      "Carbon Footprint": "5.6 kg CO₂ per kg",
      "Environmental Impact": "Moderate, similar to chicken but often seasonal",
      "Seasonality": "Commonly fall/winter",
      "Transportation": "Moderate depending on region",
      "Alternative": ["Seitan", "Eggplant"],
    },
  },
  "Seafood": {
    "Wild-Caught Salmon": {
      "image": "assets/product/wild_caught_salmon.png",
      "isFavorite": false,
      "Carbon Footprint": "3.9 kg CO₂ per kg",
      "Environmental Impact": "Can lead to overfishing, depletes populations",
      "Seasonality": "Preferable in summer and fall",
      "Transportation": "High for imports",
      "Alternative": ["Herring", "Mussels"],
    },
    "Farmed Shrimp": {
      "image": "assets/product/farmed_shrimp.png",
      "isFavorite": false,
      "Carbon Footprint": "5.9 kg CO₂ per kg",
      "Environmental Impact": "Can disrupt aquatic ecosystems",
      "Seasonality": "Year-round",
      "Transportation": "High for imported varieties",
      "Alternative": ["Mussels", "Squid"],
    },
    "Oysters": {
      "image": "assets/product/oysters.png",
      "isFavorite": false,
      "Carbon Footprint": "0.5 kg CO₂ per kg",
      "Environmental Impact": "Relatively low, filter water naturally",
      "Seasonality": "Year-round but best in winter",
      "Transportation": "Low for local sources",
      "Alternative": ["Clams", "Farmed Mussels"],
    },
  },
  "Dairy Products": {
    "Cow’s Milk": {
      "image": "assets/product/dairy_products.png",
      "isFavorite": false,
      "Carbon Footprint": "3.2 kg CO₂ per liter",
      "Environmental Impact": "Methane emissions, water-intensive",
      "Seasonality": "Year-round, best in local peak seasons",
      "Transportation": "Moderate depending on proximity to farms",
      "Alternative": ["Oat milk", "Almond milk"],
    },
    "Hard Cheese": {
      "image": "assets/product/hard_cheese.png",
      "isFavorite": false,
      "Carbon Footprint": "21.2 kg CO₂ per kg",
      "Environmental Impact": "High resource usage, methane emissions",
      "Seasonality": "Year-round",
      "Transportation": "High for imports",
      "Alternative": ["Cashew spread", "Tofu-based cheese"],
    },
    "Butter": {
      "image": "assets/product/butter.png",
      "isFavorite": false,
      "Carbon Footprint": "12 kg CO₂ per kg",
      "Environmental Impact": "High, dairy production impact",
      "Seasonality": "Year-round",
      "Transportation": "Moderate",
      "Alternative": ["Plant-based butter", "Olive oil"],
    },
  },
  "Grains and Pulses": {
    "White Rice": {
      "image": "assets/product/white_rice.png",
      "isFavorite": false,
      "Carbon Footprint": "4.5 kg CO₂ per kg",
      "Environmental Impact": "Water-intensive, methane emissions",
      "Seasonality": "Best in season from producing countries",
      "Transportation": "High for imported varieties",
      "Alternative": ["Quinoa", "Buckwheat"],
    },
    "Quinoa": {
      "image": "assets/product/quinoa.png",
      "isFavorite": false,
      "Carbon Footprint": "1.2 kg CO₂ per kg",
      "Environmental Impact": "Relatively low, soil-neutral",
      "Seasonality": "Year-round in growing regions",
      "Transportation": "High for imports",
      "Alternative": ["Buckwheat", "Millet"],
    },
    "Black Beans": {
      "image": "assets/product/black_beans.png",
      "isFavorite": false,
      "Carbon Footprint": "1.3 kg CO₂ per kg",
      "Environmental Impact": "Minimal, nitrogen-fixing crop",
      "Seasonality": "Year-round",
      "Transportation": "Low when locally grown",
      "Alternative": ["Lentils", "Chickpeas"],
    },
  },
  "Vegetables": {
    "Potatoes": {
      "image": "assets/product/potatoes.png",
      "isFavorite": false,
      "Carbon Footprint": "0.5 kg CO₂ per kg",
      "Environmental Impact": "Minimal, low water needs",
      "Seasonality": "Fall-winter for local varieties",
      "Transportation": "Low for local sourcing",
      "Alternative": ["Sweet potatoes", "Carrots"],
    },
    "Tomatoes": {
      "image": "assets/product/tomatoes.png",
      "isFavorite": false,
      "Carbon Footprint": "2.1 kg CO₂ per kg (higher in greenhouses)",
      "Environmental Impact": "Moderate if in season, high if greenhouse-grown",
      "Seasonality": "Summer for open-field varieties",
      "Transportation": "High for imported winter tomatoes",
      "Alternative": ["Bell peppers (in season)", "Zucchini"],
    },
    "Broccoli": {
      "image": "assets/product/broccoli.png",
      "isFavorite": false,
      "Carbon Footprint": "1 kg CO₂ per kg",
      "Environmental Impact": "Low, grows in cooler climates",
      "Seasonality": "Fall and winter",
      "Transportation": "Moderate if imported",
      "Alternative": ["Kale", "Cauliflower"],
    },
  },
  "Fruits": {
    "Apples": {
      "image": "assets/product/apples.png",
      "isFavorite": false,
      "Carbon Footprint": "0.4 kg CO₂ per kg",
      "Environmental Impact": "Low, especially in season",
      "Seasonality": "Fall",
      "Transportation": "Low for local harvest",
      "Alternative": ["Pears"],
    },
    "Bananas": {
      "image": "assets/product/bananas.png",
      "isFavorite": false,
      "Carbon Footprint": "0.8 kg CO₂ per kg",
      "Environmental Impact": "Moderate, imported and refrigerated",
      "Seasonality": "Year-round (imported)",
      "Transportation": "High for non-local",
      "Alternative": ["Apples or pears (when local)"],
    },
    "Avocado": {
      "image": "assets/product/avocado.png",
      "isFavorite": false,
      "Carbon Footprint": "2.5 kg CO₂ per kg",
      "Environmental Impact": "Water-intensive, high pesticide use",
      "Seasonality": "Year-round but best in winter from certain regions",
      "Transportation": "High for imported products",
      "Alternative": ["Hummus", "Nuts"],
    },
  },
  "Nuts and Seeds": {
    "Almonds": {
      "image": "assets/product/almonds.png",
      "isFavorite": false,
      "Carbon Footprint": "2.2 kg CO₂ per kg",
      "Environmental Impact": "High water usage",
      "Seasonality": "Best in season in growing areas",
      "Transportation": "High for imported",
      "Alternative": ["Walnuts", "Peanuts"],
    },
    "Cashews": {
      "image": "assets/product/cashews.png",
      "isFavorite": false,
      "Carbon Footprint": "2.4 kg CO₂ per kg",
      "Environmental Impact": "Moderate, high labor needs",
      "Seasonality": "Year-round",
      "Transportation": "High for imports",
      "Alternative": ["Almonds", "Sunflower seeds"],
    },
    "Pumpkin Seeds": {
      "image": "assets/product/pumpkin_seeds.png",
      "isFavorite": false,
      "Carbon Footprint": "0.9 kg CO₂ per kg",
      "Environmental Impact": "Low, useful byproduct of pumpkins",
      "Seasonality": "Fall",
      "Transportation": "Low if locally sourced",
      "Alternative": ["Sunflower seeds"],
    },
  },
  "Processed Foods": {
    "White Bread": {
      "image": "assets/product/white_bread.png",
      "isFavorite": false,
      "Carbon Footprint": "1.6 kg CO₂ per kg",
      "Environmental Impact": "Moderate, intensive production",
      "Seasonality": "Year-round",
      "Transportation": "Low if locally produced",
      "Alternative": ["Whole grain bread"],
    },
    "Potato Chips": {
      "image": "assets/product/potato_chips.png",
      "isFavorite": false,
      "Carbon Footprint": "2.6 kg CO₂ per kg",
      "Environmental Impact": "High energy use in processing",
      "Seasonality": "Year-round",
      "Transportation": "Moderate",
      "Alternative": ["Homemade vegetable chips"],
    },
    "Instant Ramen": {
      "image": "assets/product/instant_ramen.png",
      "isFavorite": false,
      "Carbon Footprint": "3.4 kg CO₂ per kg",
      "Environmental Impact": "High processing, packaging waste",
      "Seasonality": "Year-round",
      "Transportation": "High for imports",
      "Alternative": ["Fresh noodles", "Homemade soup"],
    },
  },
  "Oils and Fats": {
    "Olive Oil": {
      "image": "assets/product/olive_oil.png",
      "isFavorite": false,
      "Carbon Footprint": "1.8 kg CO₂ per liter",
      "Environmental Impact": "Moderate, depends on growing practices",
      "Seasonality": "Harvested in winter (Mediterranean regions)",
      "Transportation": "High for imported varieties",
      "Alternative": ["Rapeseed oil"],
    },
    "Coconut Oil": {
      "image": "assets/product/coconut_oil.png",
      "isFavorite": false,
      "Carbon Footprint": "3.2 kg CO₂ per liter",
      "Environmental Impact": "Deforestation in tropical areas",
      "Seasonality": "Year-round in tropics",
      "Transportation": "High for imports",
      "Alternative": ["Sunflower oil"],
    },
    "Palm Oil": {
      "image": "assets/product/palm_oil.png",
      "isFavorite": false,
      "Carbon Footprint": "8 kg CO₂ per liter",
      "Environmental Impact": "Major deforestation and biodiversity loss",
      "Seasonality": "Year-round",
      "Transportation": "High for imported items",
      "Alternative": ["Sunflower oil (locally sourced)"],
    },
  }
};
